# 다운받은 csv파일 월별로 합치기

In [4]:
import pandas as pd

In [4]:
#parameter
date='01'

In [5]:

df=pd.read_csv(f'data/202212/202212{date}.csv')
df.columns=['집계일자','집계시분','콘존ID','차로유형구분코드','교통량','평균속도','통행시간','정상건수',
'보정건수','통행시간표준편차','통행시간변동계수','통행시간최대값','통행시간중위값','통행시간최소값',
'퍼센타일15_85통행시간','최종변경시각','출발노드이름','출발노드위도','출발노드경도','도착노드이름','도착노드위도','도착노드경도']
df

,집계일자,집계시분,콘존ID,차로유형구분코드,교통량,평균속도,통행시간,정상건수,보정건수,통행시간표준편차,...,통행시간중위값,통행시간최소값,퍼센타일15_85통행시간,최종변경시각,출발노드이름,출발노드위도,출발노드경도,도착노드이름,도착노드위도,도착노드경도
0,20221201,0,0010CZE010,1,20,84.95,78,10,0,13.40,...,72,68,25,20221202014511,구서IC,35.246178,129.092822,영락IC,35.273493,129.108684
1,20221201,0,0010CZE011,1,22,98.60,72,10,0,5.26,...,72,63,11,20221202014511,영락IC,35.273493,129.108684,부산TG,35.279810,129.106031
2,20221201,0,0010CZE020,1,13,100.46,41,10,0,14.21,...,38,26,29,20221202014511,부산TG,35.279810,129.106031,노포IC,35.290760,129.093100
3,20221201,0,0010CZE030,1,15,100.82,294,9,1,85.39,...,288,213,172,20221202014511,노포IC,35.290760,129.093100,노포JC,NaN,NaN
4,20221201,0,0010CZE035,1,20,96.69,271,10,0,13.92,...,270,254,31,20221202014511,노포JC,NaN,NaN,양산JC,35.335115,129.040273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418267,20221201,2355,6000CZS050,1,3,115.33,55,1,0,0.00,...,55,55,0,20221202014511,김해가야Hi,NaN,NaN,대감JC,NaN,NaN
418268,20221201,2355,6000CZS060,1,15,91.80,388,10,0,8.96,...,388,370,21,20221202014511,노포JC,NaN,NaN,김해가야Hi,NaN,NaN
418269,20221201,2355,6000CZS070,1,-1,0.00,0,0,0,0.00,...,0,0,0,20221202014511,금정IC,NaN,NaN,노포JC,NaN,NaN
418270,20221201,2355,6000CZS080,1,12,98.85,156,10,0,18.94,...,159,124,40,20221202014511,기장철마IC,NaN,NaN,금정IC,NaN,NaN
418271,20221201,2355,6000CZS090,1,17,86.50,236,10,0,34.96,...,230,184,81,20221202014511,기장JC,35.280943,129.225566,기장철마IC,NaN,NaN

In [7]:
# preprocessing, 원하는 범위만 가져옴
df2=df[['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름']]

df2=df2[df2['출발노드이름'].isin(['하남JC','하남IC','동서울TG','산곡JC','경기광주IC'])&
   df['콘존ID'].isin(['0352CZS400','0352CZS410','0352CZS420','0352CZS430'])]


df2

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름
732,20221201,0,0352CZS400,33,95.94,185,204,183,175,산곡JC,경기광주IC
733,20221201,0,0352CZS410,66,95.28,160,180,159,140,동서울TG,산곡JC
734,20221201,0,0352CZS420,45,91.59,39,45,39,31,하남IC,동서울TG
735,20221201,0,0352CZS430,57,98.27,90,113,91,56,하남JC,하남IC
2168,20221201,5,0352CZS400,31,94.30,189,223,188,165,산곡JC,경기광주IC
...,...,...,...,...,...,...,...,...,...,...,...
416135,20221201,2350,0352CZS430,61,101.96,85,99,85,68,하남JC,하남IC
417568,20221201,2355,0352CZS400,38,93.32,190,210,190,169,산곡JC,경기광주IC
417569,20221201,2355,0352CZS410,63,98.37,155,173,157,133,동서울TG,산곡JC
417570,20221201,2355,0352CZS420,50,98.71,36,46,36,28,하남IC,동서울TG
417571,20221201,2355,0352CZS430,65,101.89,85,104,81,74,하남JC,하남IC

In [12]:
#파일 생성
head_df=pd.DataFrame(columns=['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름'])

head_df.to_csv('data/5분당_교통량(등교).csv', index=False)

In [13]:
import pandas as pd

# 기존 CSV 파일 불러오기
csv_file_path = 'data/5분당_교통량(등교).csv'

# 데이터프레임을 CSV 파일에 이어서 쓰기
df2.to_csv(csv_file_path, mode='a', header=False, index=False)

print("이어쓰기가 완료되었습니다.")

이어쓰기가 완료되었습니다.

# 함수로 반복 돌리기

In [18]:
month='09'

In [19]:
# 파일 생성
head_df=pd.DataFrame(columns=['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름'])

head_df.to_csv(f'data/5분당_교통량(등교){month}월.csv', index=False)

In [20]:
def read_traffic(date):
    df=pd.read_csv(f'data/2022{month}/2022{month}{date}.csv')
    df.columns=['집계일자','집계시분','콘존ID','차로유형구분코드','교통량','평균속도','통행시간','정상건수',
    '보정건수','통행시간표준편차','통행시간변동계수','통행시간최대값','통행시간중위값','통행시간최소값',
    '퍼센타일15_85통행시간','최종변경시각','출발노드이름','출발노드위도','출발노드경도','도착노드이름','도착노드위도','도착노드경도']
    
    df2=df[['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름']]
    
    df2=df2[df2['출발노드이름'].isin(['하남JC','하남IC','동서울TG','산곡JC','경기광주IC'])&
            df['콘존ID'].isin(['0352CZS400','0352CZS410','0352CZS420','0352CZS430',])]
    
    # 기존 CSV 파일 불러오기
    csv_file_path =f'data/5분당_교통량(등교){month}월.csv'

    # 데이터프레임을 CSV 파일에 이어서 쓰기
    df2.to_csv(csv_file_path, mode='a', header=False, index=False)

    print("이어쓰기가 완료되었습니다.")

In [21]:
#다운받는 사이트에서 누락된 데이터들이 있음
#데이터가 없는 것은 error가 나기 때문에 try except로 함
print(month,'월')

for date in range(1,32):
    if date<10:
        date='0'+str(date)
    try:
        read_traffic(date)
    except:
        print(date,'오류가 발생했습니다')

09 월
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
06 오류가 발생했습니다
07 오류가 발생했습니다
08 오류가 발생했습니다
09 오류가 발생했습니다
10 오류가 발생했습니다
11 오류가 발생했습니다
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
17 오류가 발생했습니다
18 오류가 발생했습니다
19 오류가 발생했습니다
20 오류가 발생했습니다
21 오류가 발생했습니다
22 오류가 발생했습니다
23 오류가 발생했습니다
24 오류가 발생했습니다
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
31 오류가 발생했습니다

'\nfor date in range(10,17):\n    date=str(date)\n    read_traffic(date)\n    \n\n    \nfor date in range(18,32):\n    date=str(date)\n    read_traffic(date)\n    \n'

# 5분당_교통량 월별 통합

In [63]:
head_df=pd.DataFrame(columns=['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름'])

head_df.to_csv(f'data/5분당_교통량(등교)통합.csv', index=False)

In [64]:
csv_file_path='data/5분당_교통량(등교)통합.csv'
for i in range(1,13):
    if i <10:
        i='0'+str(i)
    df3 =pd.read_csv(f'data/5분당_교통량(등교){i}월.csv')
    df3.to_csv(csv_file_path, mode='a', header=False, index=False)

    print("이어쓰기가 완료되었습니다.")

이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.
이어쓰기가 완료되었습니다.

In [65]:
df4=pd.read_csv('data/5분당_교통량(등교)통합.csv')
df4

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름
0,20220101,0,0352CZS400,35,95.51,186,213,186,162,산곡JC,경기광주IC
1,20220101,0,0352CZS410,92,93.06,163,172,162,155,동서울TG,산곡JC
2,20220101,0,0352CZS420,100,86.75,41,44,41,38,하남IC,동서울TG
3,20220101,0,0352CZS430,90,97.41,87,93,88,83,하남JC,하남IC
4,20220101,5,0352CZS400,39,92.57,192,209,195,178,산곡JC,경기광주IC
...,...,...,...,...,...,...,...,...,...,...,...
365179,20221231,2350,0352CZS430,59,112.85,77,105,73,63,하남JC,하남IC
365180,20221231,2355,0352CZS400,35,106.26,167,181,168,154,산곡JC,경기광주IC
365181,20221231,2355,0352CZS410,45,99.56,152,165,151,144,동서울TG,산곡JC
365182,20221231,2355,0352CZS420,46,98.83,36,40,36,29,하남IC,동서울TG
365183,20221231,2355,0352CZS430,49,112.45,77,94,76,62,하남JC,하남IC

In [72]:
#preprocessing ,원하는 형식으로 가공
df4['집계일자'] = pd.to_datetime(df4['집계일자'], format='%Y%m%d')
df4['요일'] = df4['집계일자'].dt.day_name()
df4['요일'][df4['요일']=='Monday']='월'
df4['요일'][df4['요일']=='Tuesday']='화'
df4['요일'][df4['요일']=='Wednesday']='수'
df4['요일'][df4['요일']=='Thursday']='목'
df4['요일'][df4['요일']=='Friday']='금'
df4['요일'][df4['요일']=='Saturday']='토'
df4['요일'][df4['요일']=='Sunday']='일'
df4=df4[df4['출발노드이름']!='하남JC']
df4

/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Monday']='월'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Tuesday']='화'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Wednesday']='수'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Thursday']='목'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Friday']='금'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Saturday']='토'
/var/folders/nm/26yk90l550xc1ln38d9jn04r0000gn/T/ipykernel_50348/3952241559.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['요일'][df4['요일']=='Sunday']='일'

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름,요일
0,2022-01-01,0,0352CZS400,35,95.51,186,213,186,162,산곡JC,경기광주IC,토
1,2022-01-01,0,0352CZS410,92,93.06,163,172,162,155,동서울TG,산곡JC,토
2,2022-01-01,0,0352CZS420,100,86.75,41,44,41,38,하남IC,동서울TG,토
4,2022-01-01,5,0352CZS400,39,92.57,192,209,195,178,산곡JC,경기광주IC,토
5,2022-01-01,5,0352CZS410,72,96.58,157,177,157,146,동서울TG,산곡JC,토
...,...,...,...,...,...,...,...,...,...,...,...,...
365177,2022-12-31,2350,0352CZS410,43,98.41,155,178,155,137,동서울TG,산곡JC,토
365178,2022-12-31,2350,0352CZS420,57,98.40,36,42,36,33,하남IC,동서울TG,토
365180,2022-12-31,2355,0352CZS400,35,106.26,167,181,168,154,산곡JC,경기광주IC,토
365181,2022-12-31,2355,0352CZS410,45,99.56,152,165,151,144,동서울TG,산곡JC,토
365182,2022-12-31,2355,0352CZS420,46,98.83,36,40,36,29,하남IC,동서울TG,토

In [73]:
#다시 저장
head_df=pd.DataFrame(columns=['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름','요일'])

head_df.to_csv(f'data/5분당_교통량(등교)통합.csv', index=False)
df4.to_csv(csv_file_path, mode='a', header=False, index=False)

# 최종 완성된 데이터 (5분당 교통량)

In [5]:
final_df=pd.read_csv(f'data/5분당_교통량(등교)통합.csv')
final_df

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름,요일
0,2022-01-01,0,0352CZS400,35,95.51,186,213,186,162,산곡JC,경기광주IC,토
1,2022-01-01,0,0352CZS410,92,93.06,163,172,162,155,동서울TG,산곡JC,토
2,2022-01-01,0,0352CZS420,100,86.75,41,44,41,38,하남IC,동서울TG,토
3,2022-01-01,5,0352CZS400,39,92.57,192,209,195,178,산곡JC,경기광주IC,토
4,2022-01-01,5,0352CZS410,72,96.58,157,177,157,146,동서울TG,산곡JC,토
...,...,...,...,...,...,...,...,...,...,...,...,...
273883,2022-12-31,2350,0352CZS410,43,98.41,155,178,155,137,동서울TG,산곡JC,토
273884,2022-12-31,2350,0352CZS420,57,98.40,36,42,36,33,하남IC,동서울TG,토
273885,2022-12-31,2355,0352CZS400,35,106.26,167,181,168,154,산곡JC,경기광주IC,토
273886,2022-12-31,2355,0352CZS410,45,99.56,152,165,151,144,동서울TG,산곡JC,토
273887,2022-12-31,2355,0352CZS420,46,98.83,36,40,36,29,하남IC,동서울TG,토