In [13]:
import pandas as pd

In [14]:
#parameter
date='01'

In [21]:
df=pd.read_csv(f'data/202212/202212{date}.csv')
df.columns=['집계일자','집계시분','콘존ID','차로유형구분코드','교통량','평균속도','통행시간','정상건수',
'보정건수','통행시간표준편차','통행시간변동계수','통행시간최대값','통행시간중위값','통행시간최소값',
'퍼센타일15_85통행시간','최종변경시각','출발노드이름','출발노드위도','출발노드경도','도착노드이름','도착노드위도','도착노드경도']
df

,집계일자,집계시분,콘존ID,차로유형구분코드,교통량,평균속도,통행시간,정상건수,보정건수,통행시간표준편차,...,통행시간중위값,통행시간최소값,퍼센타일15_85통행시간,최종변경시각,출발노드이름,출발노드위도,출발노드경도,도착노드이름,도착노드위도,도착노드경도
0,20221201,0,0010CZE010,1,20,84.95,78,10,0,13.40,...,72,68,25,20221202014511,구서IC,35.246178,129.092822,영락IC,35.273493,129.108684
1,20221201,0,0010CZE011,1,22,98.60,72,10,0,5.26,...,72,63,11,20221202014511,영락IC,35.273493,129.108684,부산TG,35.279810,129.106031
2,20221201,0,0010CZE020,1,13,100.46,41,10,0,14.21,...,38,26,29,20221202014511,부산TG,35.279810,129.106031,노포IC,35.290760,129.093100
3,20221201,0,0010CZE030,1,15,100.82,294,9,1,85.39,...,288,213,172,20221202014511,노포IC,35.290760,129.093100,노포JC,NaN,NaN
4,20221201,0,0010CZE035,1,20,96.69,271,10,0,13.92,...,270,254,31,20221202014511,노포JC,NaN,NaN,양산JC,35.335115,129.040273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418267,20221201,2355,6000CZS050,1,3,115.33,55,1,0,0.00,...,55,55,0,20221202014511,김해가야Hi,NaN,NaN,대감JC,NaN,NaN
418268,20221201,2355,6000CZS060,1,15,91.80,388,10,0,8.96,...,388,370,21,20221202014511,노포JC,NaN,NaN,김해가야Hi,NaN,NaN
418269,20221201,2355,6000CZS070,1,-1,0.00,0,0,0,0.00,...,0,0,0,20221202014511,금정IC,NaN,NaN,노포JC,NaN,NaN
418270,20221201,2355,6000CZS080,1,12,98.85,156,10,0,18.94,...,159,124,40,20221202014511,기장철마IC,NaN,NaN,금정IC,NaN,NaN
418271,20221201,2355,6000CZS090,1,17,86.50,236,10,0,34.96,...,230,184,81,20221202014511,기장JC,35.280943,129.225566,기장철마IC,NaN,NaN

In [33]:
df[['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값','출발노드이름','도착노드이름']]

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름
0,20221201,0,0010CZE010,20,84.95,78,104,72,68,구서IC,영락IC
1,20221201,0,0010CZE011,22,98.60,72,80,72,63,영락IC,부산TG
2,20221201,0,0010CZE020,13,100.46,41,68,38,26,부산TG,노포IC
3,20221201,0,0010CZE030,15,100.82,294,459,288,213,노포IC,노포JC
4,20221201,0,0010CZE035,20,96.69,271,299,270,254,노포JC,양산JC
...,...,...,...,...,...,...,...,...,...,...,...
418267,20221201,2355,6000CZS050,3,115.33,55,55,55,55,김해가야Hi,대감JC
418268,20221201,2355,6000CZS060,15,91.80,388,400,388,370,노포JC,김해가야Hi
418269,20221201,2355,6000CZS070,-1,0.00,0,0,0,0,금정IC,노포JC
418270,20221201,2355,6000CZS080,12,98.85,156,182,159,124,기장철마IC,금정IC
418271,20221201,2355,6000CZS090,17,86.50,236,301,230,184,기장JC,기장철마IC

In [38]:
df2=df[['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름']]

df2=df2[df2['출발노드이름'].isin(['하남JC','하남IC','동서울TG','산곡JC','경기광주IC'])&
   df['콘존ID'].isin(['0352CZS400','0352CZS410','0352CZS420','0352CZS430'])]


df2

,집계일자,집계시분,콘존ID,교통량,평균속도,통행시간,통행시간최대값,통행시간중위값,통행시간최소값,출발노드이름,도착노드이름
732,20221201,0,0352CZS400,33,95.94,185,204,183,175,산곡JC,경기광주IC
733,20221201,0,0352CZS410,66,95.28,160,180,159,140,동서울TG,산곡JC
734,20221201,0,0352CZS420,45,91.59,39,45,39,31,하남IC,동서울TG
735,20221201,0,0352CZS430,57,98.27,90,113,91,56,하남JC,하남IC
2168,20221201,5,0352CZS400,31,94.30,189,223,188,165,산곡JC,경기광주IC
...,...,...,...,...,...,...,...,...,...,...,...
416135,20221201,2350,0352CZS430,61,101.96,85,99,85,68,하남JC,하남IC
417568,20221201,2355,0352CZS400,38,93.32,190,210,190,169,산곡JC,경기광주IC
417569,20221201,2355,0352CZS410,63,98.37,155,173,157,133,동서울TG,산곡JC
417570,20221201,2355,0352CZS420,50,98.71,36,46,36,28,하남IC,동서울TG
417571,20221201,2355,0352CZS430,65,101.89,85,104,81,74,하남JC,하남IC

In [44]:
head_df=pd.DataFrame(columns=['집계일자','집계시분','콘존ID','교통량','평균속도','통행시간','통행시간최대값','통행시간중위값','통행시간최소값',
         '출발노드이름','도착노드이름'])

head_df.to_csv('data/5분당_교통량(등교).csv', index=False)

In [45]:
import pandas as pd

# 기존 CSV 파일 불러오기
existing_df = pd.read_csv('data/5분당_교통량(등교).csv')


# 두 데이터프레임을 합치기
merged_df = pd.concat([existing_df, df2], ignore_index=True)

# 합쳐진 데이터프레임을 이어서 쓰기 모드로 CSV 파일에 저장
merged_df.to_csv('data/5분당_교통량(등교).csv', mode='a', header=False, index=False)